#
# Copyright 2025 Yitao Zhang
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

import pytest
import bin2hex.bin2verilog as bin2verilog

# Test data generated by RNG tool
test_binary_61_bytes = \
    b"\x45\xD9\x58\x16\x12\x9B\x9D\x47\x96\xBF\x19\x6C\xF6\xD6\x9E\x2D" \
    b"\xE6\x59\x1A\xF1\x01\xE2\x01\xEE\xA9\xDB\xDE\xD5\x31\xE5\x79\xA3" \
    b"\x88\x7F\x61\x27\xA8\xC6\xC7\x4A\x81\x4C\xEE\x1C\x1B\x5C\xA3\x3D" \
    b"\x26\x2E\x8C\x2A\x4F\xE5\x2E\x71\xE0\x55\xFE\xF0\xAD"

test_binary_64_bytes = \
    b"\x45\xD9\x58\x16\x12\x9B\x9D\x47\x96\xBF\x19\x6C\xF6\xD6\x9E\x2D" \
    b"\xE6\x59\x1A\xF1\x01\xE2\x01\xEE\xA9\xDB\xDE\xD5\x31\xE5\x79\xA3" \
    b"\x88\x7F\x61\x27\xA8\xC6\xC7\x4A\x81\x4C\xEE\x1C\x1B\x5C\xA3\x3D" \
    b"\x26\x2E\x8C\x2A\x4F\xE5\x2E\x71\xE0\x55\xFE\xF0\xAD\xDD\xF3\x88"

test_binary_67_bytes = \
    b"\x45\xD9\x58\x16\x12\x9B\x9D\x47\x96\xBF\x19\x6C\xF6\xD6\x9E\x2D" \
    b"\xE6\x59\x1A\xF1\x01\xE2\x01\xEE\xA9\xDB\xDE\xD5\x31\xE5\x79\xA3" \
    b"\x88\x7F\x61\x27\xA8\xC6\xC7\x4A\x81\x4C\xEE\x1C\x1B\x5C\xA3\x3D" \
    b"\x26\x2E\x8C\x2A\x4F\xE5\x2E\x71\xE0\x55\xFE\xF0\xAD\xDD\xF3\x88" \
    b"\x46\xF2\x48"

# Result data and test cases

# vhex_dw1
test_hex_vhex_dw1_64_bytes = \
    "45\nD9\n58\n16\n12\n9B\n9D\n47\n96\nBF\n19\n6C\nF6\nD6\n9E\n2D\n" \
    "E6\n59\n1A\nF1\n01\nE2\n01\nEE\nA9\nDB\nDE\nD5\n31\nE5\n79\nA3\n" \
    "88\n7F\n61\n27\nA8\nC6\nC7\n4A\n81\n4C\nEE\n1C\n1B\n5C\nA3\n3D\n" \
    "26\n2E\n8C\n2A\n4F\nE5\n2E\n71\nE0\n55\nFE\nF0\nAD\nDD\nF3\n88"

def test_bin_to_vhex_dw1_64_bytes():
    output_data = bin2verilog.bin_to_vhex_dw1(test_binary_64_bytes)
    assert(output_data == test_hex_vhex_dw1_64_bytes)

test_hex_vhex_dw1_61_bytes = \
    "45\nD9\n58\n16\n12\n9B\n9D\n47\n96\nBF\n19\n6C\nF6\nD6\n9E\n2D\n" \
    "E6\n59\n1A\nF1\n01\nE2\n01\nEE\nA9\nDB\nDE\nD5\n31\nE5\n79\nA3\n" \
    "88\n7F\n61\n27\nA8\nC6\nC7\n4A\n81\n4C\nEE\n1C\n1B\n5C\nA3\n3D\n" \
    "26\n2E\n8C\n2A\n4F\nE5\n2E\n71\nE0\n55\nFE\nF0\nAD"

def test_bin_to_vhex_dw1_61_bytes():
    output_data = bin2verilog.bin_to_vhex_dw1(test_binary_61_bytes)
    assert(output_data == test_hex_vhex_dw1_61_bytes)

test_hex_vhex_dw1_67_bytes = \
    "45\nD9\n58\n16\n12\n9B\n9D\n47\n96\nBF\n19\n6C\nF6\nD6\n9E\n2D\n" \
    "E6\n59\n1A\nF1\n01\nE2\n01\nEE\nA9\nDB\nDE\nD5\n31\nE5\n79\nA3\n" \
    "88\n7F\n61\n27\nA8\nC6\nC7\n4A\n81\n4C\nEE\n1C\n1B\n5C\nA3\n3D\n" \
    "26\n2E\n8C\n2A\n4F\nE5\n2E\n71\nE0\n55\nFE\nF0\nAD\nDD\nF3\n88\n" \
    "46\nF2\n48"

def test_bin_to_vhex_dw1_67_bytes():
    output_data = bin2verilog.bin_to_vhex_dw1(test_binary_67_bytes)
    assert(output_data == test_hex_vhex_dw1_67_bytes)

# vhex_dw2
test_hex_vhex_dw2_64_bytes = \
    "D945\n1658\n9B12\n479D\nBF96\n6C19\nD6F6\n2D9E\n" \
    "59E6\nF11A\nE201\nEE01\nDBA9\nD5DE\nE531\nA379\n" \
    "7F88\n2761\nC6A8\n4AC7\n4C81\n1CEE\n5C1B\n3DA3\n" \
    "2E26\n2A8C\nE54F\n712E\n55E0\nF0FE\nDDAD\n88F3"

def test_bin_to_vhex_dw2_64_bytes():
    output_data = bin2verilog.bin_to_vhex_dw2(test_binary_64_bytes)
    assert(output_data == test_hex_vhex_dw2_64_bytes)

test_hex_vhex_dw2_61_bytes = \
    "D945\n1658\n9B12\n479D\nBF96\n6C19\nD6F6\n2D9E\n" \
    "59E6\nF11A\nE201\nEE01\nDBA9\nD5DE\nE531\nA379\n" \
    "7F88\n2761\nC6A8\n4AC7\n4C81\n1CEE\n5C1B\n3DA3\n" \
    "2E26\n2A8C\nE54F\n712E\n55E0\nF0FE\n00AD"

def test_bin_to_vhex_dw2_61_bytes():
    output_data = bin2verilog.bin_to_vhex_dw2(test_binary_61_bytes)
    assert(output_data == test_hex_vhex_dw2_61_bytes)

test_hex_vhex_dw2_67_bytes = \
    "D945\n1658\n9B12\n479D\nBF96\n6C19\nD6F6\n2D9E\n" \
    "59E6\nF11A\nE201\nEE01\nDBA9\nD5DE\nE531\nA379\n" \
    "7F88\n2761\nC6A8\n4AC7\n4C81\n1CEE\n5C1B\n3DA3\n" \
    "2E26\n2A8C\nE54F\n712E\n55E0\nF0FE\nDDAD\n88F3\n" \
    "F246\n0048"

def test_bin_to_vhex_dw2_67_bytes():
    output_data = bin2verilog.bin_to_vhex_dw2(test_binary_67_bytes)
    assert(output_data == test_hex_vhex_dw2_67_bytes)

# vhex_dw4
test_hex_vhex_dw4_64_bytes = \
    "1658D945\n479D9B12\n6C19BF96\n2D9ED6F6\n" \
    "F11A59E6\nEE01E201\nD5DEDBA9\nA379E531\n" \
    "27617F88\n4AC7C6A8\n1CEE4C81\n3DA35C1B\n" \
    "2A8C2E26\n712EE54F\nF0FE55E0\n88F3DDAD"

def test_bin_to_vhex_dw4_64_bytes():
    output_data = bin2verilog.bin_to_vhex_dw4(test_binary_64_bytes)
    assert(output_data == test_hex_vhex_dw4_64_bytes)

test_hex_vhex_dw4_61_bytes = \
    "1658D945\n479D9B12\n6C19BF96\n2D9ED6F6\n" \
    "F11A59E6\nEE01E201\nD5DEDBA9\nA379E531\n" \
    "27617F88\n4AC7C6A8\n1CEE4C81\n3DA35C1B\n" \
    "2A8C2E26\n712EE54F\nF0FE55E0\n000000AD"

def test_bin_to_vhex_dw4_61_bytes():
    output_data = bin2verilog.bin_to_vhex_dw4(test_binary_61_bytes)
    assert(output_data == test_hex_vhex_dw4_61_bytes)

test_hex_vhex_dw4_67_bytes = \
    "1658D945\n479D9B12\n6C19BF96\n2D9ED6F6\n" \
    "F11A59E6\nEE01E201\nD5DEDBA9\nA379E531\n" \
    "27617F88\n4AC7C6A8\n1CEE4C81\n3DA35C1B\n" \
    "2A8C2E26\n712EE54F\nF0FE55E0\n88F3DDAD\n" \
    "0048F246"

def test_bin_to_vhex_dw4_67_bytes():
    output_data = bin2verilog.bin_to_vhex_dw4(test_binary_67_bytes)
    assert(output_data == test_hex_vhex_dw4_67_bytes)

# vhex_dw8
test_hex_vhex_dw8_64_bytes = \
    "479D9B121658D945\n2D9ED6F66C19BF96\n" \
    "EE01E201F11A59E6\nA379E531D5DEDBA9\n" \
    "4AC7C6A827617F88\n3DA35C1B1CEE4C81\n" \
    "712EE54F2A8C2E26\n88F3DDADF0FE55E0"

def test_bin_to_vhex_dw8_64_bytes():
    output_data = bin2verilog.bin_to_vhex_dw8(test_binary_64_bytes)
    assert(output_data == test_hex_vhex_dw8_64_bytes)

test_hex_vhex_dw8_61_bytes = \
    "479D9B121658D945\n2D9ED6F66C19BF96\n" \
    "EE01E201F11A59E6\nA379E531D5DEDBA9\n" \
    "4AC7C6A827617F88\n3DA35C1B1CEE4C81\n" \
    "712EE54F2A8C2E26\n000000ADF0FE55E0"

def test_bin_to_vhex_dw8_61_bytes():
    output_data = bin2verilog.bin_to_vhex_dw8(test_binary_61_bytes)
    assert(output_data == test_hex_vhex_dw8_61_bytes)

test_hex_vhex_dw8_67_bytes = \
    "479D9B121658D945\n2D9ED6F66C19BF96\n" \
    "EE01E201F11A59E6\nA379E531D5DEDBA9\n" \
    "4AC7C6A827617F88\n3DA35C1B1CEE4C81\n" \
    "712EE54F2A8C2E26\n88F3DDADF0FE55E0\n" \
    "000000000048F246"

def test_bin_to_vhex_dw8_67_bytes():
    output_data = bin2verilog.bin_to_vhex_dw8(test_binary_67_bytes)
    assert(output_data == test_hex_vhex_dw8_67_bytes)

# vhex_dw16
test_hex_vhex_dw16_64_bytes = \
    "2D9ED6F66C19BF96479D9B121658D945\n" \
    "A379E531D5DEDBA9EE01E201F11A59E6\n" \
    "3DA35C1B1CEE4C814AC7C6A827617F88\n" \
    "88F3DDADF0FE55E0712EE54F2A8C2E26"

def test_bin_to_vhex_dw16_64_bytes():
    output_data = bin2verilog.bin_to_vhex_dw16(test_binary_64_bytes)
    assert(output_data == test_hex_vhex_dw16_64_bytes)

test_hex_vhex_dw16_61_bytes = \
    "2D9ED6F66C19BF96479D9B121658D945\n" \
    "A379E531D5DEDBA9EE01E201F11A59E6\n" \
    "3DA35C1B1CEE4C814AC7C6A827617F88\n" \
    "000000ADF0FE55E0712EE54F2A8C2E26"

def test_bin_to_vhex_dw16_61_bytes():
    output_data = bin2verilog.bin_to_vhex_dw16(test_binary_61_bytes)
    assert(output_data == test_hex_vhex_dw16_61_bytes)

test_hex_vhex_dw16_67_bytes = \
    "2D9ED6F66C19BF96479D9B121658D945\n" \
    "A379E531D5DEDBA9EE01E201F11A59E6\n" \
    "3DA35C1B1CEE4C814AC7C6A827617F88\n" \
    "88F3DDADF0FE55E0712EE54F2A8C2E26\n" \
    "0000000000000000000000000048F246"

def test_bin_to_vhex_dw16_67_bytes():
    output_data = bin2verilog.bin_to_vhex_dw16(test_binary_67_bytes)
    assert(output_data == test_hex_vhex_dw16_67_bytes)

# vhex_addr_dw1
test_hex_vhex_addr_dw1_64_bytes_32_align = \
    "@00000000 45 D9 58 16 12 9B 9D 47 96 BF 19 6C F6 D6 9E 2D E6 59 1A F1 01 E2 01 EE A9 DB DE D5 31 E5 79 A3\n" \
    "@00000020 88 7F 61 27 A8 C6 C7 4A 81 4C EE 1C 1B 5C A3 3D 26 2E 8C 2A 4F E5 2E 71 E0 55 FE F0 AD DD F3 88"

def test_bin_to_vhex_addr_dw1_64_bytes_32_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw1(test_binary_64_bytes, 0, 32)
    assert(output_data == test_hex_vhex_addr_dw1_64_bytes_32_align)

test_hex_vhex_addr_dw1_61_bytes_32_align = \
    "@00000000 45 D9 58 16 12 9B 9D 47 96 BF 19 6C F6 D6 9E 2D E6 59 1A F1 01 E2 01 EE A9 DB DE D5 31 E5 79 A3\n" \
    "@00000020 88 7F 61 27 A8 C6 C7 4A 81 4C EE 1C 1B 5C A3 3D 26 2E 8C 2A 4F E5 2E 71 E0 55 FE F0 AD"

def test_bin_to_vhex_addr_dw1_61_bytes_32_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw1(test_binary_61_bytes, 0, 32)
    assert(output_data == test_hex_vhex_addr_dw1_61_bytes_32_align)

test_hex_vhex_addr_dw1_67_bytes_32_align = \
    "@00000000 45 D9 58 16 12 9B 9D 47 96 BF 19 6C F6 D6 9E 2D E6 59 1A F1 01 E2 01 EE A9 DB DE D5 31 E5 79 A3\n" \
    "@00000020 88 7F 61 27 A8 C6 C7 4A 81 4C EE 1C 1B 5C A3 3D 26 2E 8C 2A 4F E5 2E 71 E0 55 FE F0 AD DD F3 88\n" \
    "@00000040 46 F2 48"

def test_bin_to_vhex_addr_dw1_67_bytes_32_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw1(test_binary_67_bytes, 0, 32)
    assert(output_data == test_hex_vhex_addr_dw1_67_bytes_32_align)

test_hex_vhex_addr_dw1_64_bytes_31_align = \
    "@00000000 45 D9 58 16 12 9B 9D 47 96 BF 19 6C F6 D6 9E 2D E6 59 1A F1 01 E2 01 EE A9 DB DE D5 31 E5 79\n" \
    "@0000001F A3 88 7F 61 27 A8 C6 C7 4A 81 4C EE 1C 1B 5C A3 3D 26 2E 8C 2A 4F E5 2E 71 E0 55 FE F0 AD DD\n" \
    "@0000003E F3 88"

def test_bin_to_vhex_addr_dw1_64_bytes_31_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw1(test_binary_64_bytes, 0, 31)
    assert(output_data == test_hex_vhex_addr_dw1_64_bytes_31_align)

test_hex_vhex_addr_dw1_61_bytes_31_align = \
    "@00000000 45 D9 58 16 12 9B 9D 47 96 BF 19 6C F6 D6 9E 2D E6 59 1A F1 01 E2 01 EE A9 DB DE D5 31 E5 79\n" \
    "@0000001F A3 88 7F 61 27 A8 C6 C7 4A 81 4C EE 1C 1B 5C A3 3D 26 2E 8C 2A 4F E5 2E 71 E0 55 FE F0 AD" \

def test_bin_to_vhex_addr_dw1_61_bytes_31_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw1(test_binary_61_bytes, 0, 31)
    assert(output_data == test_hex_vhex_addr_dw1_61_bytes_31_align)

test_hex_vhex_addr_dw1_67_bytes_31_align = \
    "@00000000 45 D9 58 16 12 9B 9D 47 96 BF 19 6C F6 D6 9E 2D E6 59 1A F1 01 E2 01 EE A9 DB DE D5 31 E5 79\n" \
    "@0000001F A3 88 7F 61 27 A8 C6 C7 4A 81 4C EE 1C 1B 5C A3 3D 26 2E 8C 2A 4F E5 2E 71 E0 55 FE F0 AD DD\n" \
    "@0000003E F3 88 46 F2 48"

def test_bin_to_vhex_addr_dw1_67_bytes_31_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw1(test_binary_67_bytes, 0, 31)
    assert(output_data == test_hex_vhex_addr_dw1_67_bytes_31_align)

test_hex_vhex_addr_dw1_64_bytes_37_align = \
    "@00000000 45 D9 58 16 12 9B 9D 47 96 BF 19 6C F6 D6 9E 2D E6 59 1A F1 01 E2 01 EE A9 DB DE D5 31 E5 79 A3 88 7F 61 27 A8\n" \
    "@00000025 C6 C7 4A 81 4C EE 1C 1B 5C A3 3D 26 2E 8C 2A 4F E5 2E 71 E0 55 FE F0 AD DD F3 88"

def test_bin_to_vhex_addr_dw1_64_bytes_37_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw1(test_binary_64_bytes, 0, 37)
    assert(output_data == test_hex_vhex_addr_dw1_64_bytes_37_align)

test_hex_vhex_addr_dw1_61_bytes_37_align = \
    "@00000000 45 D9 58 16 12 9B 9D 47 96 BF 19 6C F6 D6 9E 2D E6 59 1A F1 01 E2 01 EE A9 DB DE D5 31 E5 79 A3 88 7F 61 27 A8\n" \
    "@00000025 C6 C7 4A 81 4C EE 1C 1B 5C A3 3D 26 2E 8C 2A 4F E5 2E 71 E0 55 FE F0 AD"

def test_bin_to_vhex_addr_dw1_61_bytes_37_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw1(test_binary_61_bytes, 0, 37)
    assert(output_data == test_hex_vhex_addr_dw1_61_bytes_37_align)

test_hex_vhex_addr_dw1_67_bytes_37_align = \
    "@00000000 45 D9 58 16 12 9B 9D 47 96 BF 19 6C F6 D6 9E 2D E6 59 1A F1 01 E2 01 EE A9 DB DE D5 31 E5 79 A3 88 7F 61 27 A8\n" \
    "@00000025 C6 C7 4A 81 4C EE 1C 1B 5C A3 3D 26 2E 8C 2A 4F E5 2E 71 E0 55 FE F0 AD DD F3 88 46 F2 48"

def test_bin_to_vhex_addr_dw1_67_bytes_37_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw1(test_binary_67_bytes, 0, 37)
    assert(output_data == test_hex_vhex_addr_dw1_67_bytes_37_align)

# vhex_addr_dw2
test_hex_vhex_addr_dw2_64_bytes_32_align = \
    "@00000000 D945 1658 9B12 479D BF96 6C19 D6F6 2D9E 59E6 F11A E201 EE01 DBA9 D5DE E531 A379\n" \
    "@00000020 7F88 2761 C6A8 4AC7 4C81 1CEE 5C1B 3DA3 2E26 2A8C E54F 712E 55E0 F0FE DDAD 88F3"

def test_bin_to_vhex_addr_dw2_64_bytes_32_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw2(test_binary_64_bytes, 0, 32)
    assert(output_data == test_hex_vhex_addr_dw2_64_bytes_32_align)

test_hex_vhex_addr_dw2_61_bytes_32_align = \
    "@00000000 D945 1658 9B12 479D BF96 6C19 D6F6 2D9E 59E6 F11A E201 EE01 DBA9 D5DE E531 A379\n" \
    "@00000020 7F88 2761 C6A8 4AC7 4C81 1CEE 5C1B 3DA3 2E26 2A8C E54F 712E 55E0 F0FE 00AD"

def test_bin_to_vhex_addr_dw2_61_bytes_32_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw2(test_binary_61_bytes, 0, 32)
    assert(output_data == test_hex_vhex_addr_dw2_61_bytes_32_align)

test_hex_vhex_addr_dw2_67_bytes_32_align = \
    "@00000000 D945 1658 9B12 479D BF96 6C19 D6F6 2D9E 59E6 F11A E201 EE01 DBA9 D5DE E531 A379\n" \
    "@00000020 7F88 2761 C6A8 4AC7 4C81 1CEE 5C1B 3DA3 2E26 2A8C E54F 712E 55E0 F0FE DDAD 88F3\n" \
    "@00000040 F246 0048"

def test_bin_to_vhex_addr_dw2_67_bytes_32_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw2(test_binary_67_bytes, 0, 32)
    assert(output_data == test_hex_vhex_addr_dw2_67_bytes_32_align)

test_hex_vhex_addr_dw2_64_bytes_31_align = \
    "@00000000 D945 1658 9B12 479D BF96 6C19 D6F6 2D9E 59E6 F11A E201 EE01 DBA9 D5DE E531 A379\n" \
    "@00000020 7F88 2761 C6A8 4AC7 4C81 1CEE 5C1B 3DA3 2E26 2A8C E54F 712E 55E0 F0FE DDAD 88F3"

def test_bin_to_vhex_addr_dw2_64_bytes_31_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw2(test_binary_64_bytes, 0, 31)
    assert(output_data == test_hex_vhex_addr_dw2_64_bytes_31_align)

test_hex_vhex_addr_dw2_61_bytes_31_align = \
    "@00000000 D945 1658 9B12 479D BF96 6C19 D6F6 2D9E 59E6 F11A E201 EE01 DBA9 D5DE E531 A379\n" \
    "@00000020 7F88 2761 C6A8 4AC7 4C81 1CEE 5C1B 3DA3 2E26 2A8C E54F 712E 55E0 F0FE 00AD"

def test_bin_to_vhex_addr_dw2_61_bytes_31_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw2(test_binary_61_bytes, 0, 31)
    assert(output_data == test_hex_vhex_addr_dw2_61_bytes_31_align)

test_hex_vhex_addr_dw2_67_bytes_31_align = \
    "@00000000 D945 1658 9B12 479D BF96 6C19 D6F6 2D9E 59E6 F11A E201 EE01 DBA9 D5DE E531 A379\n" \
    "@00000020 7F88 2761 C6A8 4AC7 4C81 1CEE 5C1B 3DA3 2E26 2A8C E54F 712E 55E0 F0FE DDAD 88F3\n" \
    "@00000040 F246 0048"

def test_bin_to_vhex_addr_dw2_67_bytes_31_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw2(test_binary_67_bytes, 0, 31)
    assert(output_data == test_hex_vhex_addr_dw2_67_bytes_31_align)

test_hex_vhex_addr_dw2_64_bytes_37_align = \
    "@00000000 D945 1658 9B12 479D BF96 6C19 D6F6 2D9E 59E6 F11A E201 EE01 DBA9 D5DE E531 A379 7F88 2761 C6A8\n" \
    "@00000026 4AC7 4C81 1CEE 5C1B 3DA3 2E26 2A8C E54F 712E 55E0 F0FE DDAD 88F3"

def test_bin_to_vhex_addr_dw2_64_bytes_37_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw2(test_binary_64_bytes, 0, 37)
    assert(output_data == test_hex_vhex_addr_dw2_64_bytes_37_align)

test_hex_vhex_addr_dw2_61_bytes_37_align = \
    "@00000000 D945 1658 9B12 479D BF96 6C19 D6F6 2D9E 59E6 F11A E201 EE01 DBA9 D5DE E531 A379 7F88 2761 C6A8\n" \
    "@00000026 4AC7 4C81 1CEE 5C1B 3DA3 2E26 2A8C E54F 712E 55E0 F0FE 00AD"

def test_bin_to_vhex_addr_dw2_61_bytes_37_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw2(test_binary_61_bytes, 0, 37)
    assert(output_data == test_hex_vhex_addr_dw2_61_bytes_37_align)

test_hex_vhex_addr_dw2_67_bytes_37_align = \
    "@00000000 D945 1658 9B12 479D BF96 6C19 D6F6 2D9E 59E6 F11A E201 EE01 DBA9 D5DE E531 A379 7F88 2761 C6A8\n" \
    "@00000026 4AC7 4C81 1CEE 5C1B 3DA3 2E26 2A8C E54F 712E 55E0 F0FE DDAD 88F3 F246 0048"

def test_bin_to_vhex_addr_dw2_67_bytes_37_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw2(test_binary_67_bytes, 0, 37)
    assert(output_data == test_hex_vhex_addr_dw2_67_bytes_37_align)

def test_bin_to_vhex_addr_dw2_invalid_address():
    with pytest.raises(ValueError):
        output_data = bin2verilog.bin_to_vhex_addr_dw2(test_binary_64_bytes, 0x1, 32)

# vhex_addr_dw4
test_hex_vhex_addr_dw4_64_bytes_32_align = \
    "@00000000 1658D945 479D9B12 6C19BF96 2D9ED6F6 F11A59E6 EE01E201 D5DEDBA9 A379E531\n" \
    "@00000020 27617F88 4AC7C6A8 1CEE4C81 3DA35C1B 2A8C2E26 712EE54F F0FE55E0 88F3DDAD"

def test_bin_to_vhex_addr_dw4_64_bytes_32_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw4(test_binary_64_bytes, 0, 32)
    assert(output_data == test_hex_vhex_addr_dw4_64_bytes_32_align)

test_hex_vhex_addr_dw4_61_bytes_32_align = \
    "@00000000 1658D945 479D9B12 6C19BF96 2D9ED6F6 F11A59E6 EE01E201 D5DEDBA9 A379E531\n" \
    "@00000020 27617F88 4AC7C6A8 1CEE4C81 3DA35C1B 2A8C2E26 712EE54F F0FE55E0 000000AD"

def test_bin_to_vhex_addr_dw4_61_bytes_32_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw4(test_binary_61_bytes, 0, 32)
    assert(output_data == test_hex_vhex_addr_dw4_61_bytes_32_align)

test_hex_vhex_addr_dw4_67_bytes_32_align = \
    "@00000000 1658D945 479D9B12 6C19BF96 2D9ED6F6 F11A59E6 EE01E201 D5DEDBA9 A379E531\n" \
    "@00000020 27617F88 4AC7C6A8 1CEE4C81 3DA35C1B 2A8C2E26 712EE54F F0FE55E0 88F3DDAD\n" \
    "@00000040 0048F246"

def test_bin_to_vhex_addr_dw4_67_bytes_32_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw4(test_binary_67_bytes, 0, 32)
    assert(output_data == test_hex_vhex_addr_dw4_67_bytes_32_align)

test_hex_vhex_addr_dw4_64_bytes_31_align = \
    "@00000000 1658D945 479D9B12 6C19BF96 2D9ED6F6 F11A59E6 EE01E201 D5DEDBA9 A379E531\n" \
    "@00000020 27617F88 4AC7C6A8 1CEE4C81 3DA35C1B 2A8C2E26 712EE54F F0FE55E0 88F3DDAD"

def test_bin_to_vhex_addr_dw4_64_bytes_31_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw4(test_binary_64_bytes, 0, 31)
    assert(output_data == test_hex_vhex_addr_dw4_64_bytes_31_align)

test_hex_vhex_addr_dw4_61_bytes_31_align = \
    "@00000000 1658D945 479D9B12 6C19BF96 2D9ED6F6 F11A59E6 EE01E201 D5DEDBA9 A379E531\n" \
    "@00000020 27617F88 4AC7C6A8 1CEE4C81 3DA35C1B 2A8C2E26 712EE54F F0FE55E0 000000AD"

def test_bin_to_vhex_addr_dw4_61_bytes_31_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw4(test_binary_61_bytes, 0, 31)
    assert(output_data == test_hex_vhex_addr_dw4_61_bytes_31_align)

test_hex_vhex_addr_dw4_67_bytes_31_align = \
    "@00000000 1658D945 479D9B12 6C19BF96 2D9ED6F6 F11A59E6 EE01E201 D5DEDBA9 A379E531\n" \
    "@00000020 27617F88 4AC7C6A8 1CEE4C81 3DA35C1B 2A8C2E26 712EE54F F0FE55E0 88F3DDAD\n" \
    "@00000040 0048F246"

def test_bin_to_vhex_addr_dw4_67_bytes_31_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw4(test_binary_67_bytes, 0, 31)
    assert(output_data == test_hex_vhex_addr_dw4_67_bytes_31_align)

test_hex_vhex_addr_dw4_64_bytes_37_align = \
    "@00000000 1658D945 479D9B12 6C19BF96 2D9ED6F6 F11A59E6 EE01E201 D5DEDBA9 A379E531 27617F88 4AC7C6A8\n" \
    "@00000028 1CEE4C81 3DA35C1B 2A8C2E26 712EE54F F0FE55E0 88F3DDAD"

def test_bin_to_vhex_addr_dw4_64_bytes_37_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw4(test_binary_64_bytes, 0, 37)
    assert(output_data == test_hex_vhex_addr_dw4_64_bytes_37_align)

test_hex_vhex_addr_dw4_61_bytes_37_align = \
    "@00000000 1658D945 479D9B12 6C19BF96 2D9ED6F6 F11A59E6 EE01E201 D5DEDBA9 A379E531 27617F88 4AC7C6A8\n" \
    "@00000028 1CEE4C81 3DA35C1B 2A8C2E26 712EE54F F0FE55E0 000000AD"

def test_bin_to_vhex_addr_dw4_61_bytes_37_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw4(test_binary_61_bytes, 0, 37)
    assert(output_data == test_hex_vhex_addr_dw4_61_bytes_37_align)

test_hex_vhex_addr_dw4_67_bytes_37_align = \
    "@00000000 1658D945 479D9B12 6C19BF96 2D9ED6F6 F11A59E6 EE01E201 D5DEDBA9 A379E531 27617F88 4AC7C6A8\n" \
    "@00000028 1CEE4C81 3DA35C1B 2A8C2E26 712EE54F F0FE55E0 88F3DDAD 0048F246"

def test_bin_to_vhex_addr_dw4_67_bytes_37_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw4(test_binary_67_bytes, 0, 37)
    assert(output_data == test_hex_vhex_addr_dw4_67_bytes_37_align)

def test_bin_to_vhex_addr_dw4_invalid_address():
    with pytest.raises(ValueError):
        output_data = bin2verilog.bin_to_vhex_addr_dw4(test_binary_64_bytes, 0x2, 32)

# vhex_addr_dw8
test_hex_vhex_addr_dw8_64_bytes_32_align = \
    "@00000000 479D9B121658D945 2D9ED6F66C19BF96 EE01E201F11A59E6 A379E531D5DEDBA9\n" \
    "@00000020 4AC7C6A827617F88 3DA35C1B1CEE4C81 712EE54F2A8C2E26 88F3DDADF0FE55E0"

def test_bin_to_vhex_addr_dw8_64_bytes_32_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw8(test_binary_64_bytes, 0, 32)
    assert(output_data == test_hex_vhex_addr_dw8_64_bytes_32_align)

test_hex_vhex_addr_dw8_61_bytes_32_align = \
    "@00000000 479D9B121658D945 2D9ED6F66C19BF96 EE01E201F11A59E6 A379E531D5DEDBA9\n" \
    "@00000020 4AC7C6A827617F88 3DA35C1B1CEE4C81 712EE54F2A8C2E26 000000ADF0FE55E0"

def test_bin_to_vhex_addr_dw8_61_bytes_32_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw8(test_binary_61_bytes, 0, 32)
    assert(output_data == test_hex_vhex_addr_dw8_61_bytes_32_align)

test_hex_vhex_addr_dw8_67_bytes_32_align = \
    "@00000000 479D9B121658D945 2D9ED6F66C19BF96 EE01E201F11A59E6 A379E531D5DEDBA9\n" \
    "@00000020 4AC7C6A827617F88 3DA35C1B1CEE4C81 712EE54F2A8C2E26 88F3DDADF0FE55E0\n" \
    "@00000040 000000000048F246"

def test_bin_to_vhex_addr_dw8_67_bytes_32_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw8(test_binary_67_bytes, 0, 32)
    assert(output_data == test_hex_vhex_addr_dw8_67_bytes_32_align)

test_hex_vhex_addr_dw8_64_bytes_31_align = \
    "@00000000 479D9B121658D945 2D9ED6F66C19BF96 EE01E201F11A59E6 A379E531D5DEDBA9\n" \
    "@00000020 4AC7C6A827617F88 3DA35C1B1CEE4C81 712EE54F2A8C2E26 88F3DDADF0FE55E0"

def test_bin_to_vhex_addr_dw8_64_bytes_31_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw8(test_binary_64_bytes, 0, 31)
    assert(output_data == test_hex_vhex_addr_dw8_64_bytes_31_align)

test_hex_vhex_addr_dw8_61_bytes_31_align = \
    "@00000000 479D9B121658D945 2D9ED6F66C19BF96 EE01E201F11A59E6 A379E531D5DEDBA9\n" \
    "@00000020 4AC7C6A827617F88 3DA35C1B1CEE4C81 712EE54F2A8C2E26 000000ADF0FE55E0"

def test_bin_to_vhex_addr_dw8_61_bytes_31_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw8(test_binary_61_bytes, 0, 31)
    assert(output_data == test_hex_vhex_addr_dw8_61_bytes_31_align)

test_hex_vhex_addr_dw8_67_bytes_31_align = \
    "@00000000 479D9B121658D945 2D9ED6F66C19BF96 EE01E201F11A59E6 A379E531D5DEDBA9\n" \
    "@00000020 4AC7C6A827617F88 3DA35C1B1CEE4C81 712EE54F2A8C2E26 88F3DDADF0FE55E0\n" \
    "@00000040 000000000048F246"

def test_bin_to_vhex_addr_dw8_67_bytes_31_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw8(test_binary_67_bytes, 0, 31)
    assert(output_data == test_hex_vhex_addr_dw8_67_bytes_31_align)

test_hex_vhex_addr_dw8_64_bytes_37_align = \
    "@00000000 479D9B121658D945 2D9ED6F66C19BF96 EE01E201F11A59E6 A379E531D5DEDBA9 4AC7C6A827617F88\n" \
    "@00000028 3DA35C1B1CEE4C81 712EE54F2A8C2E26 88F3DDADF0FE55E0"

def test_bin_to_vhex_addr_dw8_64_bytes_37_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw8(test_binary_64_bytes, 0, 37)
    assert(output_data == test_hex_vhex_addr_dw8_64_bytes_37_align)

test_hex_vhex_addr_dw8_61_bytes_37_align = \
    "@00000000 479D9B121658D945 2D9ED6F66C19BF96 EE01E201F11A59E6 A379E531D5DEDBA9 4AC7C6A827617F88\n" \
    "@00000028 3DA35C1B1CEE4C81 712EE54F2A8C2E26 000000ADF0FE55E0"

def test_bin_to_vhex_addr_dw8_61_bytes_37_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw8(test_binary_61_bytes, 0, 37)
    assert(output_data == test_hex_vhex_addr_dw8_61_bytes_37_align)

test_hex_vhex_addr_dw8_67_bytes_37_align = \
    "@00000000 479D9B121658D945 2D9ED6F66C19BF96 EE01E201F11A59E6 A379E531D5DEDBA9 4AC7C6A827617F88\n" \
    "@00000028 3DA35C1B1CEE4C81 712EE54F2A8C2E26 88F3DDADF0FE55E0 000000000048F246"

def test_bin_to_vhex_addr_dw8_67_bytes_37_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw8(test_binary_67_bytes, 0, 37)
    assert(output_data == test_hex_vhex_addr_dw8_67_bytes_37_align)

def test_bin_to_vhex_addr_dw8_invalid_address():
    with pytest.raises(ValueError):
        output_data = bin2verilog.bin_to_vhex_addr_dw8(test_binary_64_bytes, 0x4, 32)

# vhex_addr_dw16
test_hex_vhex_addr_dw16_64_bytes_32_align = \
    "@00000000 2D9ED6F66C19BF96479D9B121658D945 A379E531D5DEDBA9EE01E201F11A59E6\n" \
    "@00000020 3DA35C1B1CEE4C814AC7C6A827617F88 88F3DDADF0FE55E0712EE54F2A8C2E26"

def test_bin_to_vhex_addr_dw16_64_bytes_32_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw16(test_binary_64_bytes, 0, 32)
    assert(output_data == test_hex_vhex_addr_dw16_64_bytes_32_align)

test_hex_vhex_addr_dw16_61_bytes_32_align = \
    "@00000000 2D9ED6F66C19BF96479D9B121658D945 A379E531D5DEDBA9EE01E201F11A59E6\n" \
    "@00000020 3DA35C1B1CEE4C814AC7C6A827617F88 000000ADF0FE55E0712EE54F2A8C2E26"

def test_bin_to_vhex_addr_dw16_61_bytes_32_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw16(test_binary_61_bytes, 0, 32)
    assert(output_data == test_hex_vhex_addr_dw16_61_bytes_32_align)

test_hex_vhex_addr_dw16_67_bytes_32_align = \
    "@00000000 2D9ED6F66C19BF96479D9B121658D945 A379E531D5DEDBA9EE01E201F11A59E6\n" \
    "@00000020 3DA35C1B1CEE4C814AC7C6A827617F88 88F3DDADF0FE55E0712EE54F2A8C2E26\n" \
    "@00000040 0000000000000000000000000048F246"

def test_bin_to_vhex_addr_dw16_67_bytes_32_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw16(test_binary_67_bytes, 0, 32)
    assert(output_data == test_hex_vhex_addr_dw16_67_bytes_32_align)

test_hex_vhex_addr_dw16_64_bytes_31_align = \
    "@00000000 2D9ED6F66C19BF96479D9B121658D945 A379E531D5DEDBA9EE01E201F11A59E6\n" \
    "@00000020 3DA35C1B1CEE4C814AC7C6A827617F88 88F3DDADF0FE55E0712EE54F2A8C2E26"

def test_bin_to_vhex_addr_dw16_64_bytes_31_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw16(test_binary_64_bytes, 0, 31)
    assert(output_data == test_hex_vhex_addr_dw16_64_bytes_31_align)

test_hex_vhex_addr_dw16_61_bytes_31_align = \
    "@00000000 2D9ED6F66C19BF96479D9B121658D945 A379E531D5DEDBA9EE01E201F11A59E6\n" \
    "@00000020 3DA35C1B1CEE4C814AC7C6A827617F88 000000ADF0FE55E0712EE54F2A8C2E26"

def test_bin_to_vhex_addr_dw16_61_bytes_31_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw16(test_binary_61_bytes, 0, 31)
    assert(output_data == test_hex_vhex_addr_dw16_61_bytes_31_align)

test_hex_vhex_addr_dw16_67_bytes_31_align = \
    "@00000000 2D9ED6F66C19BF96479D9B121658D945 A379E531D5DEDBA9EE01E201F11A59E6\n" \
    "@00000020 3DA35C1B1CEE4C814AC7C6A827617F88 88F3DDADF0FE55E0712EE54F2A8C2E26\n" \
    "@00000040 0000000000000000000000000048F246"

def test_bin_to_vhex_addr_dw16_67_bytes_31_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw16(test_binary_67_bytes, 0, 31)
    assert(output_data == test_hex_vhex_addr_dw16_67_bytes_31_align)

test_hex_vhex_addr_dw16_64_bytes_37_align = \
    "@00000000 2D9ED6F66C19BF96479D9B121658D945 A379E531D5DEDBA9EE01E201F11A59E6 3DA35C1B1CEE4C814AC7C6A827617F88\n" \
    "@00000030 88F3DDADF0FE55E0712EE54F2A8C2E26"

def test_bin_to_vhex_addr_dw16_64_bytes_37_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw16(test_binary_64_bytes, 0, 37)
    assert(output_data == test_hex_vhex_addr_dw16_64_bytes_37_align)

test_hex_vhex_addr_dw16_61_bytes_37_align = \
    "@00000000 2D9ED6F66C19BF96479D9B121658D945 A379E531D5DEDBA9EE01E201F11A59E6 3DA35C1B1CEE4C814AC7C6A827617F88\n" \
    "@00000030 000000ADF0FE55E0712EE54F2A8C2E26"

def test_bin_to_vhex_addr_dw16_61_bytes_37_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw16(test_binary_61_bytes, 0, 37)
    assert(output_data == test_hex_vhex_addr_dw16_61_bytes_37_align)

test_hex_vhex_addr_dw16_67_bytes_37_align = \
    "@00000000 2D9ED6F66C19BF96479D9B121658D945 A379E531D5DEDBA9EE01E201F11A59E6 3DA35C1B1CEE4C814AC7C6A827617F88\n" \
    "@00000030 88F3DDADF0FE55E0712EE54F2A8C2E26 0000000000000000000000000048F246"

def test_bin_to_vhex_addr_dw16_67_bytes_37_align():
    output_data = bin2verilog.bin_to_vhex_addr_dw16(test_binary_67_bytes, 0, 37)
    assert(output_data == test_hex_vhex_addr_dw16_67_bytes_37_align)

def test_bin_to_vhex_addr_dw16_invalid_address():
    with pytest.raises(ValueError):
        output_data = bin2verilog.bin_to_vhex_addr_dw16(test_binary_64_bytes, 0x4, 32)

# vbin_dw1
test_hex_vbin_dw1_64_bytes = \
    "01000101\n11011001\n01011000\n00010110\n00010010\n10011011\n10011101\n01000111\n" \
    "10010110\n10111111\n00011001\n01101100\n11110110\n11010110\n10011110\n00101101\n" \
    "11100110\n01011001\n00011010\n11110001\n00000001\n11100010\n00000001\n11101110\n" \
    "10101001\n11011011\n11011110\n11010101\n00110001\n11100101\n01111001\n10100011\n" \
    "10001000\n01111111\n01100001\n00100111\n10101000\n11000110\n11000111\n01001010\n" \
    "10000001\n01001100\n11101110\n00011100\n00011011\n01011100\n10100011\n00111101\n" \
    "00100110\n00101110\n10001100\n00101010\n01001111\n11100101\n00101110\n01110001\n" \
    "11100000\n01010101\n11111110\n11110000\n10101101\n11011101\n11110011\n10001000"

def test_bin_to_vbin_dw1_64_bytes():
    output_data = bin2verilog.bin_to_vbin_dw1(test_binary_64_bytes)
    assert(output_data == test_hex_vbin_dw1_64_bytes)

test_hex_vbin_dw1_61_bytes = \
    "01000101\n11011001\n01011000\n00010110\n00010010\n10011011\n10011101\n01000111\n" \
    "10010110\n10111111\n00011001\n01101100\n11110110\n11010110\n10011110\n00101101\n" \
    "11100110\n01011001\n00011010\n11110001\n00000001\n11100010\n00000001\n11101110\n" \
    "10101001\n11011011\n11011110\n11010101\n00110001\n11100101\n01111001\n10100011\n" \
    "10001000\n01111111\n01100001\n00100111\n10101000\n11000110\n11000111\n01001010\n" \
    "10000001\n01001100\n11101110\n00011100\n00011011\n01011100\n10100011\n00111101\n" \
    "00100110\n00101110\n10001100\n00101010\n01001111\n11100101\n00101110\n01110001\n" \
    "11100000\n01010101\n11111110\n11110000\n10101101"

def test_bin_to_vbin_dw1_61_bytes():
    output_data = bin2verilog.bin_to_vbin_dw1(test_binary_61_bytes)
    assert(output_data == test_hex_vbin_dw1_61_bytes)

test_hex_vbin_dw1_67_bytes = \
    "01000101\n11011001\n01011000\n00010110\n00010010\n10011011\n10011101\n01000111\n" \
    "10010110\n10111111\n00011001\n01101100\n11110110\n11010110\n10011110\n00101101\n" \
    "11100110\n01011001\n00011010\n11110001\n00000001\n11100010\n00000001\n11101110\n" \
    "10101001\n11011011\n11011110\n11010101\n00110001\n11100101\n01111001\n10100011\n" \
    "10001000\n01111111\n01100001\n00100111\n10101000\n11000110\n11000111\n01001010\n" \
    "10000001\n01001100\n11101110\n00011100\n00011011\n01011100\n10100011\n00111101\n" \
    "00100110\n00101110\n10001100\n00101010\n01001111\n11100101\n00101110\n01110001\n" \
    "11100000\n01010101\n11111110\n11110000\n10101101\n11011101\n11110011\n10001000\n" \
    "01000110\n11110010\n01001000"

def test_bin_to_vbin_dw1_67_bytes():
    output_data = bin2verilog.bin_to_vbin_dw1(test_binary_67_bytes)
    assert(output_data == test_hex_vbin_dw1_67_bytes)

# vbin_dw2
test_hex_vbin_dw2_64_bytes = \
    "1101100101000101\n0001011001011000\n1001101100010010\n0100011110011101\n" \
    "1011111110010110\n0110110000011001\n1101011011110110\n0010110110011110\n" \
    "0101100111100110\n1111000100011010\n1110001000000001\n1110111000000001\n" \
    "1101101110101001\n1101010111011110\n1110010100110001\n1010001101111001\n" \
    "0111111110001000\n0010011101100001\n1100011010101000\n0100101011000111\n" \
    "0100110010000001\n0001110011101110\n0101110000011011\n0011110110100011\n" \
    "0010111000100110\n0010101010001100\n1110010101001111\n0111000100101110\n" \
    "0101010111100000\n1111000011111110\n1101110110101101\n1000100011110011"

def test_bin_to_vbin_dw2_64_bytes():
    output_data = bin2verilog.bin_to_vbin_dw2(test_binary_64_bytes)
    assert(output_data == test_hex_vbin_dw2_64_bytes)

test_hex_vbin_dw2_61_bytes = \
    "1101100101000101\n0001011001011000\n1001101100010010\n0100011110011101\n" \
    "1011111110010110\n0110110000011001\n1101011011110110\n0010110110011110\n" \
    "0101100111100110\n1111000100011010\n1110001000000001\n1110111000000001\n" \
    "1101101110101001\n1101010111011110\n1110010100110001\n1010001101111001\n" \
    "0111111110001000\n0010011101100001\n1100011010101000\n0100101011000111\n" \
    "0100110010000001\n0001110011101110\n0101110000011011\n0011110110100011\n" \
    "0010111000100110\n0010101010001100\n1110010101001111\n0111000100101110\n" \
    "0101010111100000\n1111000011111110\n0000000010101101"

def test_bin_to_vbin_dw2_61_bytes():
    output_data = bin2verilog.bin_to_vbin_dw2(test_binary_61_bytes)
    assert(output_data == test_hex_vbin_dw2_61_bytes)

test_hex_vbin_dw2_67_bytes = \
    "1101100101000101\n0001011001011000\n1001101100010010\n0100011110011101\n" \
    "1011111110010110\n0110110000011001\n1101011011110110\n0010110110011110\n" \
    "0101100111100110\n1111000100011010\n1110001000000001\n1110111000000001\n" \
    "1101101110101001\n1101010111011110\n1110010100110001\n1010001101111001\n" \
    "0111111110001000\n0010011101100001\n1100011010101000\n0100101011000111\n" \
    "0100110010000001\n0001110011101110\n0101110000011011\n0011110110100011\n" \
    "0010111000100110\n0010101010001100\n1110010101001111\n0111000100101110\n" \
    "0101010111100000\n1111000011111110\n1101110110101101\n1000100011110011\n" \
    "1111001001000110\n0000000001001000"

def test_bin_to_vbin_dw2_67_bytes():
    output_data = bin2verilog.bin_to_vbin_dw2(test_binary_67_bytes)
    assert(output_data == test_hex_vbin_dw2_67_bytes)

# vbin_dw4
test_hex_vbin_dw4_64_bytes = \
    "00010110010110001101100101000101\n01000111100111011001101100010010\n" \
    "01101100000110011011111110010110\n00101101100111101101011011110110\n" \
    "11110001000110100101100111100110\n11101110000000011110001000000001\n" \
    "11010101110111101101101110101001\n10100011011110011110010100110001\n" \
    "00100111011000010111111110001000\n01001010110001111100011010101000\n" \
    "00011100111011100100110010000001\n00111101101000110101110000011011\n" \
    "00101010100011000010111000100110\n01110001001011101110010101001111\n" \
    "11110000111111100101010111100000\n10001000111100111101110110101101"

def test_bin_to_vbin_dw4_64_bytes():
    output_data = bin2verilog.bin_to_vbin_dw4(test_binary_64_bytes)
    assert(output_data == test_hex_vbin_dw4_64_bytes)

test_hex_vbin_dw4_61_bytes = \
    "00010110010110001101100101000101\n01000111100111011001101100010010\n" \
    "01101100000110011011111110010110\n00101101100111101101011011110110\n" \
    "11110001000110100101100111100110\n11101110000000011110001000000001\n" \
    "11010101110111101101101110101001\n10100011011110011110010100110001\n" \
    "00100111011000010111111110001000\n01001010110001111100011010101000\n" \
    "00011100111011100100110010000001\n00111101101000110101110000011011\n" \
    "00101010100011000010111000100110\n01110001001011101110010101001111\n" \
    "11110000111111100101010111100000\n00000000000000000000000010101101"

def test_bin_to_vbin_dw4_61_bytes():
    output_data = bin2verilog.bin_to_vbin_dw4(test_binary_61_bytes)
    assert(output_data == test_hex_vbin_dw4_61_bytes)

test_hex_vbin_dw4_67_bytes = \
    "00010110010110001101100101000101\n01000111100111011001101100010010\n" \
    "01101100000110011011111110010110\n00101101100111101101011011110110\n" \
    "11110001000110100101100111100110\n11101110000000011110001000000001\n" \
    "11010101110111101101101110101001\n10100011011110011110010100110001\n" \
    "00100111011000010111111110001000\n01001010110001111100011010101000\n" \
    "00011100111011100100110010000001\n00111101101000110101110000011011\n" \
    "00101010100011000010111000100110\n01110001001011101110010101001111\n" \
    "11110000111111100101010111100000\n10001000111100111101110110101101\n" \
    "00000000010010001111001001000110"

def test_bin_to_vbin_dw4_67_bytes():
    output_data = bin2verilog.bin_to_vbin_dw4(test_binary_67_bytes)
    assert(output_data == test_hex_vbin_dw4_67_bytes)

# vbin_dw8
test_hex_vbin_dw8_64_bytes = \
    "0100011110011101100110110001001000010110010110001101100101000101\n" \
    "0010110110011110110101101111011001101100000110011011111110010110\n" \
    "1110111000000001111000100000000111110001000110100101100111100110\n" \
    "1010001101111001111001010011000111010101110111101101101110101001\n" \
    "0100101011000111110001101010100000100111011000010111111110001000\n" \
    "0011110110100011010111000001101100011100111011100100110010000001\n" \
    "0111000100101110111001010100111100101010100011000010111000100110\n" \
    "1000100011110011110111011010110111110000111111100101010111100000"

def test_bin_to_vbin_dw8_64_bytes():
    output_data = bin2verilog.bin_to_vbin_dw8(test_binary_64_bytes)
    assert(output_data == test_hex_vbin_dw8_64_bytes)

test_hex_vbin_dw8_61_bytes = \
    "0100011110011101100110110001001000010110010110001101100101000101\n" \
    "0010110110011110110101101111011001101100000110011011111110010110\n" \
    "1110111000000001111000100000000111110001000110100101100111100110\n" \
    "1010001101111001111001010011000111010101110111101101101110101001\n" \
    "0100101011000111110001101010100000100111011000010111111110001000\n" \
    "0011110110100011010111000001101100011100111011100100110010000001\n" \
    "0111000100101110111001010100111100101010100011000010111000100110\n" \
    "0000000000000000000000001010110111110000111111100101010111100000"

def test_bin_to_vbin_dw8_61_bytes():
    output_data = bin2verilog.bin_to_vbin_dw8(test_binary_61_bytes)
    assert(output_data == test_hex_vbin_dw8_61_bytes)

test_hex_vbin_dw8_67_bytes = \
    "0100011110011101100110110001001000010110010110001101100101000101\n" \
    "0010110110011110110101101111011001101100000110011011111110010110\n" \
    "1110111000000001111000100000000111110001000110100101100111100110\n" \
    "1010001101111001111001010011000111010101110111101101101110101001\n" \
    "0100101011000111110001101010100000100111011000010111111110001000\n" \
    "0011110110100011010111000001101100011100111011100100110010000001\n" \
    "0111000100101110111001010100111100101010100011000010111000100110\n" \
    "1000100011110011110111011010110111110000111111100101010111100000\n" \
    "0000000000000000000000000000000000000000010010001111001001000110"

def test_bin_to_vbin_dw8_67_bytes():
    output_data = bin2verilog.bin_to_vbin_dw8(test_binary_67_bytes)
    assert(output_data == test_hex_vbin_dw8_67_bytes)

# vbin_dw16
test_hex_vbin_dw16_64_bytes = \
    "00101101100111101101011011110110011011000001100110111111100101100100011110011101100110110001001000010110010110001101100101000101\n" \
    "10100011011110011110010100110001110101011101111011011011101010011110111000000001111000100000000111110001000110100101100111100110\n" \
    "00111101101000110101110000011011000111001110111001001100100000010100101011000111110001101010100000100111011000010111111110001000\n" \
    "10001000111100111101110110101101111100001111111001010101111000000111000100101110111001010100111100101010100011000010111000100110"

def test_bin_to_vbin_dw16_64_bytes():
    output_data = bin2verilog.bin_to_vbin_dw16(test_binary_64_bytes)
    assert(output_data == test_hex_vbin_dw16_64_bytes)

test_hex_vbin_dw16_61_bytes = \
    "00101101100111101101011011110110011011000001100110111111100101100100011110011101100110110001001000010110010110001101100101000101\n" \
    "10100011011110011110010100110001110101011101111011011011101010011110111000000001111000100000000111110001000110100101100111100110\n" \
    "00111101101000110101110000011011000111001110111001001100100000010100101011000111110001101010100000100111011000010111111110001000\n" \
    "00000000000000000000000010101101111100001111111001010101111000000111000100101110111001010100111100101010100011000010111000100110"

def test_bin_to_vbin_dw16_61_bytes():
    output_data = bin2verilog.bin_to_vbin_dw16(test_binary_61_bytes)
    assert(output_data == test_hex_vbin_dw16_61_bytes)

test_hex_vbin_dw16_67_bytes = \
    "00101101100111101101011011110110011011000001100110111111100101100100011110011101100110110001001000010110010110001101100101000101\n" \
    "10100011011110011110010100110001110101011101111011011011101010011110111000000001111000100000000111110001000110100101100111100110\n" \
    "00111101101000110101110000011011000111001110111001001100100000010100101011000111110001101010100000100111011000010111111110001000\n" \
    "10001000111100111101110110101101111100001111111001010101111000000111000100101110111001010100111100101010100011000010111000100110\n" \
    "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010010001111001001000110"

def test_bin_to_vbin_dw16_67_bytes():
    output_data = bin2verilog.bin_to_vbin_dw16(test_binary_67_bytes)
    assert(output_data == test_hex_vbin_dw16_67_bytes)

